config/routes.rb
Rails.application.routes.draw do
  resources :songs, except: [:index, :edit, :show, :update, :destroy] do
    collection { post :import}
  end
  get 'subscriptions', to: 'subscription#index'
  devise_for :users, :paths => 'users'
  resources :users do
    resources :payments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :broadcasters, except: [:show]
  resources :genres
  resources :datalists, only: [:new, :create]
  get 'payments/pending', to: 'payments#pendingpayments'
  get 'broadcasters/manage', to: 'broadcasters#manage'
  get 'administration/users', to: 'admins#manageusers'
  get 'administration', to: 'admins#index'
  get 'billboard', to: 'billboards#index'
  get 'billboard/top_100', to: 'billboards#top_100'
  get 'billboard/top_100_pdf', to: 'billboards#top_100_pdf'
  get 'billboard/top_latino', to: 'billboards#top_latino'
  get 'billboard/top_latino_pdf', to: 'billboards#top_latino_pdf'
  get 'billboard/top_tradicional', to: 'billboards#top_tradicional'
  get 'billboard/top_tradicional_pdf', to: 'billboards#top_tradicional_pdf'
  get 'billboard/top_balada', to: 'billboards#top_balada'
  get 'billboard/top_balada_pdf', to: 'billboards#top_balada_pdf'
  get 'billboard/top_salsa', to: 'billboards#top_salsa'
  get 'billboard/top_salsa_pdf', to: 'billboards#top_salsa_pdf'
  get 'billboard/top_pop', to: 'billboards#top_pop'
  get 'billboard/top_pop_pdf', to: 'billboards#top_pop_pdf'
  get 'billboard/top_rock', to: 'billboards#top_rock'
  get 'billboard/top_rock_pdf', to: 'billboards#top_rock_pdf'
  get 'billboard/top_emisoras', to: 'billboards#top_emisoras'
  get 'billboard/top_emisoras_pdf', to: 'billboards#top_emisoras_pdf'
  get 'contact', to: 'contact#index'
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_one_attached :picture
  validate :correct_file_type

  private

  def correct_file_type
    if picture.attached? && !picture.content_type.in?(%w(image/jpg image/jpeg image/png))
      errors.add(:picture, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png')
    end
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, notice: '¡ Género Musical Agregado Correctamente !'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @genre.update(genre_params)
      redirect_to genres_path, notice: '¡ Género Musical Actualizado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Actualizar el registro seleccionado !'
    end
  end

  def destroy
    if @genre.destroy
      redirect_to genres_path, notice: '¡ Género Musical Eliminado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Elimina el registro seleccionado !'
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name, :picture)
  end

  def resolve_layout
    case action_name
    when "index", "new"
      "admin"
    end
  end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/edit.html.haml
= render 'shared/genre_form'

app/views/genres/index.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_path, method: 'get', id: 'botonvolver' do
      .row.d-flex
        = image_tag 'izquierda.svg'
        .ml-1.align-self-center
          Volver
.row.headercontent
  .col-3.pl-4
    = image_tag ('pop.svg'), heigth: '200px', width:'200px', class: ''
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Gestión de Género Musical
    .row.contenttext.text-muted
      En esta sección podras agregar, editar y/o eliminar géneros musicales.
    - if @genres.present?
      .row.signindiv.mt-3
        .col.d-flex.justify-content-end
          = link_to new_genre_path, method: 'get', class: 'btn', id: 'signinbutton' do
            Agregar Genero musical
#lineaseparadora.mt-2
  %hr
- if @genres.present?
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-6
      %table{class: 'table table-hover table-bordered', id: 'genretable'}
        %thead.text-center#genretablehead
          %tr
            %th{colspan: '2'} Géneros Musicales Registrados
        %tbody.text-center#genretablebody
          - @genres.each do |genre|
            %tr
              %td= genre.name
              %td.dropdown.dropright
                %button#dropdownMenuButton.btn{type: 'button', 'data-toggle':"dropdown", 'aria-haspopup': "true", 'aria-expanded': "false"}
                  = image_tag 'menu.svg'
                .dropdown-menu#dropdownmenu{"aria-labelledby" => "dropdownMenuButton"}
                  .dropdown-item#dropdownmenuitem
                    = link_to edit_genre_path(genre.id), class: '', id: 'optionbutton' do
                      .row
                        .col-3
                          = image_tag 'pencil.svg'
                        .col-9
                          Editar
                  .dropdown-item#dropdownmenuitem
                    = link_to genre_path(genre.id), method: 'delete', data: {confirm: '¿Esta seguro de eliminar este género?'}, class: '', id: 'optionbutton' do
                      .row
                        .col-3
                          = image_tag 'bin.svg'
                        .col-9
                          Eliminar
- else
  .row.bodycontent
    .col-12
      .row.justify-content-center.mt-5
        = link_to new_genre_path, method: 'get' do
          = image_tag 'añadirpago.svg'
      .row.justify-content-center
        = link_to new_genre_path, method: 'get', id: 'forgot-password' do
          Presiona para agregar un nuevo género musical

app/views/genres/new.html.haml
= render 'shared/genre_form'