config/routes.rb
Rails.application.routes.draw do
  resources :songs, except: [:index, :edit, :show, :update, :destroy] do
    collection { post :import}
  end
  get 'subscriptions', to: 'subscription#index'
  devise_for :users, :paths => 'users'
  resources :users do
    resources :payments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :broadcasters, except: [:show]
  resources :genres
  resources :datalists, only: [:new, :create]
  get 'payments/pending', to: 'payments#pendingpayments'
  get 'broadcasters/manage', to: 'broadcasters#manage'
  get 'administration/users', to: 'admins#manageusers'
  get 'administration', to: 'admins#index'
  get 'billboard', to: 'billboards#index'
  get 'billboard/top_100', to: 'billboards#top_100'
  get 'billboard/top_100_pdf', to: 'billboards#top_100_pdf'
  get 'billboard/top_latino', to: 'billboards#top_latino'
  get 'billboard/top_latino_pdf', to: 'billboards#top_latino_pdf'
  get 'billboard/top_tradicional', to: 'billboards#top_tradicional'
  get 'billboard/top_tradicional_pdf', to: 'billboards#top_tradicional_pdf'
  get 'billboard/top_balada', to: 'billboards#top_balada'
  get 'billboard/top_balada_pdf', to: 'billboards#top_balada_pdf'
  get 'billboard/top_salsa', to: 'billboards#top_salsa'
  get 'billboard/top_salsa_pdf', to: 'billboards#top_salsa_pdf'
  get 'billboard/top_pop', to: 'billboards#top_pop'
  get 'billboard/top_pop_pdf', to: 'billboards#top_pop_pdf'
  get 'billboard/top_rock', to: 'billboards#top_rock'
  get 'billboard/top_rock_pdf', to: 'billboards#top_rock_pdf'
  get 'billboard/top_emisoras', to: 'billboards#top_emisoras'
  get 'billboard/top_emisoras_pdf', to: 'billboards#top_emisoras_pdf'
  get 'contact', to: 'contact#index'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  enum paid_out: [:pendiente, :procesado]
  validates :invoice, :paid_out, presence: true
  validate :correct_file_type
  has_one_attached :invoice

  # after_update :set_user_active
  accepts_nested_attributes_for :user, update_only: true

  private

    def correct_file_type
      if invoice.attached? && !invoice.content_type.in?(%w(image/jpg image/jpeg image/png application/pdf))
        errors.add(:invoice, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .pdf')
      end
    end

    # def set_user_active
    #   @user = User.find(params[:id])
    #   @user.status = 'activo'
    #   @user.save
    # end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin, except: [:new, :create]
  before_action :set_payment, only: [:edit, :update]
  layout :resolve_layout
def index
  @user = User.find(params[:user_id])
  @payments = Payment.all.where(user_id: @user).order(created_at: :desc)
end

def pendingpayments
  @payments = Payment.all.where(paid_out: 0)
end

def new
  @user = User.find(params[:user_id])
  @payment = Payment.new()
end

def create
  @user = User.find(params[:user_id])
  @payment = @user.payments.build(payment_params)
  respond_to do |format|
    if @payment.save
      UserMailer.send_pay(@user).deliver
      UserMailer.confirmation(@user).deliver
      format.html { redirect_to new_user_payment_path, notice: '¡ Recibo enviado correctamente, una vez confirmado el pago, recibirá una notificación por correo electrónico!' }
    else
      format.html { redirect_to new_user_payment_path, alert: '¡ Pago no enviado, el formato del archivo es incorrecto!'  }
    end
  end
end

def edit
  @user = User.find(params[:user_id])
end

def update
  @user = User.find(params[:user_id])
  if @payment.update(payment_params)
    UserMailer.notify(@user).deliver
    redirect_to user_payments_path(@user,@payments), notice: 'Registros procesados correctamente'
  else
    redirect_to payments_pending_path, alert: 'No se pudo procesar el pago seleccionado'
  end

  # render json: @payment
end

private

def authenticate_admin
  if current_user.role != 'admin'
    redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
  end
end

def set_payment
  @payment = Payment.find(params[:id])
end

def payment_params
  params.require(:payment).permit(:paid_out, :invoice, user_attributes: [:status, :suscription_date])
end

def user_params
  params.require(:user).permit(status:[], suscription_date: [])
end

def resolve_layout
  case action_name
  when "index", "pendingpayments", "edit"
    "admin"
  end
end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to payments_pending_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3.pl-5
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Procesar pago seleccionado
    .row.contenttext.text-muted
      En esta sección debes seleccionar el Estatus de Pago y procesarlo una vez hayas verificado el archivo enviado por el usuario para cancelar su cuota correspondiente.
= form_with(model: [@user, @payment], local: true) do |form|
  .row.form-group.justify-content-center.mt-5
    .col-6.form-label
      = form.label :paid_out, 'Estatus del Pago'
      = form.select :paid_out, ['procesado'], {include_blank: 'Seleccione'}, {class:'form-control custom-select text-capitalize'} #Payment.paid_outs.keys
      = form.fields_for :user, @user do |userform|
        = userform.hidden_field :status, value: 'activo'
        = userform.hidden_field :suscription_date, value: Time.now.strftime('%Y-%m-%d')
  .row.form-group.justify-content-center
    .col-6.form-label
      .actions
        .text-center= form.submit 'Procesar Pago', class: 'btn', id: 'form-user-button'

app/views/payments/index.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_users_path, method: 'get', id: 'botonvolver' do
      .row.d-flex
        = image_tag 'izquierda.svg'
        .ml-1.align-self-center
          Volver
.row.headercontent
  .col-3.pl-5.mt-2
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Verificación de Pagos por Usuario
    .row.contenttext.text-muted
      En esta sección se muestra el historial de pagos realizado por el cliente seleccionado y a su vez se puede visualizar su estatus y el archivo que anexó en su oportunidad.
#lineaseparadora.mt-2
  %hr
-if @payments.present?
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-8
      %table{class: 'table table-hover table-bordered', id: 'genreborder'}
        %thead.text-center
          %tr
            %th{colspan: '4'} Pagos realizados por el usuario
          %tr.font-italic
            %th Nombre y apellido
            %th Email
            %th Estatus del pago
            %th Adjuntos
        %tbody.text-center
          - @payments.each do |payment|
            %tr
              %td= payment.user.name
              %td= payment.user.email
              -if payment.paid_out == 'pendiente'
                %td{class:'text-capitalize text-warning'}= payment.paid_out
              -else
                %td{class:'text-capitalize text-success'}= payment.paid_out
              %td= link_to 'Ver Pago',url_for(payment.invoice), target: "_blank", id: 'see-payment'
              -# -if payment.paid_out == 'pendiente'
              -#   %td= link_to 'Procesar', edit_user_payment_path(payment.user_id, payment.id), class:'btn', id: 'form-user-button'
- else
  .row.mt-5.d-flex.justify-content-center.bodycontent
    .col-6
      .row.d-flex.justify-content-center
        = image_tag 'credit_card.svg', height: '250px', width: '300px', class: 'processing-paid'
  .row.mt-3.d-flex.justify-content-center.bodycontent.mb-5
    %h3{class: 'font-italic text-center'} No Existen Pagos Realizados por el Usuario

app/views/payments/new.html.haml
.row.headercontent
  .col-3.pl-5
    = image_tag 'radio.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Mi cuenta
    .row.contenttext.text-muted
      En esta sección realizaras la carga del archivo en formato .PDF, .JPG, .JPEG o .PNG del pago que hayas realizado para cancelar la cuota mensual de la suscripción a los beneficios otorgados por ser miembro exclusivo de Monitor Radial.
#lineaseparadora.mt-2
  %hr
-if (@user.status == 'activo')
  = render 'shared/new_payment_user_active'
- else
  = render 'shared/new_payment_user_inactive', locals: {user: @user, payment: @payment}

app/views/payments/pendingpayments.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_users_path, method: 'get', id: 'botonvolver' do
      .row.d-flex
        = image_tag 'izquierda.svg'
        .ml-1.align-self-center
          Volver
.row.headercontent
  .col-3.pl-5.mt-2
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Verificación de Pagos Pendientes
    .row.contenttext.text-muted
      En esta sección se puedrá verificar todos aquellos pagos que se encuentren en proceso de verificación, de todos aquellos usuarios que enviaron su boucher de soporte a través de Monitor Radial.
#lineaseparadora.mt-2
  %hr

-if @payments.present?
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-9
      %table{class: 'table table-hover table-bordered', id: 'genreborder'}
        %thead.text-center
          %tr
            %th{colspan: '5'} Pagos pendientes por Procesar
          %tr.font-italic
            %th Nombre y apellido
            %th Email
            %th Estatus del pago
            %th Adjuntos
            %th Acción
        %tbody.text-center
          - @payments.each do |payment|
            %tr
              %td= payment.user.name
              %td= payment.user.email
              %td{class:'text-capitalize text-warning'}= payment.paid_out
              %td= link_to 'Ver Pago', url_for(payment.invoice), target: "_blank", id: 'see-payment'
              %td= link_to 'Procesar', edit_user_payment_path(user_id: payment.user.id, id: payment.id), class:'btn', id: 'form-user-button'
-else
  .row.mt-5.justify-content-center.bodycontent
    .col-6
      .row.d-flex.justify-content-center
        = image_tag 'undraw_no_data_qbuo.svg', height: '250px', width: '400px', class: 'processing-paid'
  .row.mt-3.d-flex.justify-content-center.bodycontent.mb-5
    %h3{class: 'font-italic'} No Existen Registros por procesar